export const GET = 'rooms/GET'
export const ADD = 'rooms/ADD'
export const SHOW = 'rooms/SHOW'
export const UPDATE = 'rooms/UPDATE'
export const DELETE = 'rooms/DELETE'
export const STOREUSERNAME = 'rooms/STOREUSERNAME'
export const ADDMESSAGE = 'rooms/ADDMESSAGE'
